# RogerOS: sin partición de swap (ya usa memoria comprimida zram); todo el disco para el sistema
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 300M
userSwapChoices:
    - none
    - file
initialSwapChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
alwaysShowPartitionLabels: true
drawNestedPartitions: false
