# RogerOS: ajustes del núcleo para escritorio y juegos
vm.swappiness = 20
vm.vfs_cache_pressure = 50
vm.dirty_ratio = 10
vm.dirty_background_ratio = 5
# Muchos juegos (Proton, Star Citizen, CS2...) necesitan más mapas de memoria
vm.max_map_count = 2147483642
# Red más ágil
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fastopen = 3
# Más archivos vigilados (editores de código, Steam)
fs.inotify.max_user_watches = 524288
kernel.nmi_watchdog = 0
